# Checked-in API keys for one-step collaborator builds.
speechmatics.api.key=ofqMHzf6XuZRbzoitMZoSUUYSb6OuTG3
speechmatics.api.url=wss://eu2.rt.speechmatics.com/v2
amap.api.key=56eb07b84591e8d7c3c86f3dbcb7d62b
google.maps.api.key=
